#!/bin/sh
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-CO-QC_CTGAAGCT-GTCAGTAC_L007_R1.fastq.gz
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-CO-QC_CTGAAGCT-GTCAGTAC_L007_R2.fastq.gz
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-CO-QE_TAATGCGC-AGGCTATA_L007_R1.fastq.gz
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-CO-QE_TAATGCGC-AGGCTATA_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-CO-VC_TAATGCGC-AGGATAGG_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-CO-VC_TAATGCGC-AGGATAGG_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-CO-VE_TAATGCGC-GCCTCTAT_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-CO-VE_TAATGCGC-GCCTCTAT_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-GV-QC_TAATGCGC-TCAGAGCC_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-GV-QC_TAATGCGC-TCAGAGCC_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-GV-QE_TAATGCGC-CTTCGCCT_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-GV-QE_TAATGCGC-CTTCGCCT_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-GV-VC_TAATGCGC-ACGTCCTG_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-GV-VC_TAATGCGC-ACGTCCTG_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-GV-VE_TAATGCGC-TAAGATTA_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-GV-VE_TAATGCGC-TAAGATTA_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-RE-QC_TAATGCGC-GTCAGTAC_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-RE-QC_TAATGCGC-GTCAGTAC_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-RE-QE_CGGCTATG-AGGCTATA_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-RE-QE_CGGCTATG-AGGCTATA_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-RE-VC_CGGCTATG-AGGATAGG_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-RE-VC_CGGCTATG-AGGATAGG_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-RE-VE_CGGCTATG-GCCTCTAT_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/BI-RE-VE_CGGCTATG-GCCTCTAT_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-CO-QC_GAATTCGT-GCCTCTAT_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-CO-QC_GAATTCGT-GCCTCTAT_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-CO-QE_GAATTCGT-AGGATAGG_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-CO-QE_GAATTCGT-AGGATAGG_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-CO-VC_ATTCAGAA-CTTCGCCT_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-CO-VC_ATTCAGAA-CTTCGCCT_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-CO-VE_ATTCAGAA-TCAGAGCC_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-CO-VE_ATTCAGAA-TCAGAGCC_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-GV-QC_ATTCAGAA-GTCAGTAC_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-GV-QC_ATTCAGAA-GTCAGTAC_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-GV-QE_GAATTCGT-AGGCTATA_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-GV-QE_GAATTCGT-AGGCTATA_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-GV-VC_ATTCAGAA-AGGATAGG_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-GV-VC_ATTCAGAA-AGGATAGG_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-GV-VE_ATTCAGAA-GCCTCTAT_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-GV-VE_ATTCAGAA-GCCTCTAT_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-RE-QC_ATTCAGAA-TAAGATTA_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-RE-QC_ATTCAGAA-TAAGATTA_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-RE-QE_ATTCAGAA-ACGTCCTG_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-RE-QE_ATTCAGAA-ACGTCCTG_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-RE-VC_ATTCAGAA-AGGCTATA_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-RE-VC_ATTCAGAA-AGGCTATA_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-RE-VE_GAGATTCC-GTCAGTAC_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EN-RE-VE_GAGATTCC-GTCAGTAC_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-CO-QC_GAATTCGT-TCAGAGCC_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-CO-QC_GAATTCGT-TCAGAGCC_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-CO-QE_GAATTCGT-CTTCGCCT_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-CO-QE_GAATTCGT-CTTCGCCT_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-CO-VC_GAATTCGT-ACGTCCTG_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-CO-VC_GAATTCGT-ACGTCCTG_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-CO-VE_GAATTCGT-TAAGATTA_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-CO-VE_GAATTCGT-TAAGATTA_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-GV-QC_GAATTCGT-GTCAGTAC_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-GV-QC_GAATTCGT-GTCAGTAC_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-GV-QE_CTGAAGCT-AGGCTATA_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-GV-QE_CTGAAGCT-AGGCTATA_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-GV-VC_CTGAAGCT-AGGATAGG_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-GV-VC_CTGAAGCT-AGGATAGG_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-GV-VE_CTGAAGCT-GCCTCTAT_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-GV-VE_CTGAAGCT-GCCTCTAT_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-RE-QC_CTGAAGCT-TCAGAGCC_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-RE-QC_CTGAAGCT-TCAGAGCC_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-RE-QE_CTGAAGCT-CTTCGCCT_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-RE-QE_CTGAAGCT-CTTCGCCT_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-RE-VC_CTGAAGCT-ACGTCCTG_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-RE-VC_CTGAAGCT-ACGTCCTG_L007_R2.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-RE-VE_CTGAAGCT-TAAGATTA_L007_R1.fastq.gz 
wget http://ng6.toulouse.inra.fr/fileadmin/data/run/0ee92cff3/EP-RE-VE_CTGAAGCT-TAAGATTA_L007_R2.fastq.gz